matsu2018te/mercariB

app/assets/stylesheets/application.css
application.scssへのfont-awesomeの追記
font-awsomeの有効化するため
=> Set font-awesome

app/assets/stylesheets/application.css, app/assets/stylesheets/modules/_reset.scss
reset.scssファイルの追加
意図しないSCSSの崩れを防ぐため
=> Add reset.scss

app/controllers/application_controller.rb, db/migrate/20181212100724_add_user_info_to_users.rb
ユーザーテーブルに必要なカラム追加
ユーザー情報登録に必要なため
=> add columns to user

README.md, app/models/address.rb, app/models/user.rb, db/migrate/20181215052216_create_addresses.rb, db/schema.rb
=> Create address table

app/assets/javascripts/mypage_action.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixin/_user-config.scss, app/assets/stylesheets/modules/_logout.scss, app/assets/stylesheets/modules/_mypage.scss, app/assets/stylesheets/modules/_side_bar.scss, app/views/mypages/_logout.html.haml, app/views/mypages/_mypage.html.haml, app/views/mypages/_notification.html.haml, app/views/mypages/_side_bar.html.haml, app/views/users/destroy.html.haml, app/views/users/edit.html.haml, config/routes.rb
ユーザーマイページ内logoutページの作成 
マイページ内、プロフィール編集ページ・ログアウトページと合わせて
ユーザーログアウトができるように
各ページ調整
=> Create logout page

app/controllers/credits_controller.rb
=> クレジットカード画面編集

app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_top_content.scss, app/views/home/_brand_content.html.haml, app/views/home/_category_content.html.haml, app/views/home/_header.html.haml
ログイン中か否かで表示されるメニューが変更されるよう修正
トップページの商品一覧表示レイアウトを一部修正
#Why
会員か否かで利用できる機能を切り分けるため
UX向上の為
=> グローバルメニュー修正

db/migrate/20181221114703_remove_name_from_users.rb
=> edit_first_name

README.md, db/migrate/20181221114703_remove_name_from_users.rb, db/migrate/20181222042722_change_datatypedelivery_date_of_products.rb, db/schema.rb
=> Edit_database

app/models/product.rb, db/seeds.rb
#what
シードファイルの作成
#why
サーバーにデータベースのサンプル情報を登録するため
=> Create seeds file

app/controllers/users/registrations_controller.rb, app/views/home/_brand_content.html.haml, app/views/home/_category_content.html.haml, app/views/products/new.html.haml, spec/factories/users.rb
=> データベース再設計に伴うディレクトリ内のカラム名修正

app/views/devise/registrations/registration.html.haml
=> edit_reCAPTCHA

app/assets/stylesheets/modules/_footer.scss, app/controllers/products_controller.rb, app/views/home/_footer.html.haml, app/views/products/_product_user-item.haml, app/views/products/show.html.haml
商品一覧の画像表示のバグ修正
商品一覧に画像を表示させるため
=> debug variables

app/controllers/credits_controller.rb, app/views/credits/index.html.haml, app/views/devise/registrations/address.html.haml, app/views/devise/registrations/credit.html.haml, app/views/devise/registrations/done.html.haml, app/views/devise/registrations/registration.html.haml, app/views/devise/registrations/signup.html.haml, app/views/devise/registrations/sms_confirmation.html.haml, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_footer.html.haml, app/views/devise/shared/_header.html.haml, app/views/mypages/_side_bar.html.haml, app/views/users/edit.html.haml, config/routes.rb
ルーティングの見直しとリンクの追加・修正
ルーティングの重複などが見られるため
=> ルーティングの整理とリンクの修正

app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/views/devise/registrations/registration.html.haml, app/views/devise/sessions/new.html.haml
reCAPTCHの一時的な無効化
本番環境で適用できないため
=> reCAPTCHの無効化

app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/views/devise/registrations/registration.html.haml, app/views/devise/sessions/new.html.haml, config/deploy.rb, config/secrets.yml
=> reCAPTCHの再設定

app/assets/javascripts/application.js, app/assets/javascripts/product_image_upload.js
jsファイルのコンフリクト内容の削除
意図しないエラーを防ぐため
=> fix conflicts

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/product-detail.js, app/assets/stylesheets/modules/_product-detail.scss, app/controllers/products_controller.rb, app/views/layouts/application.html.erb, app/views/products/_product_user-item.haml, app/views/products/new.html.haml, app/views/products/show.html.haml
商品詳細画面の画像が消えるバグ修正
ユーザー関連商品のcss修正
カテゴリーブランド関連のif文追加
適切な商品を提示するため
=> Debug product detail

app/controllers/users_controller.rb, app/views/users/edit.html.haml, config/routes.rb
プロフィール編集機能の実装
マークアップのみで、実際の編集機能は未実装だったため。
=> 【サーバーサイド】プロフィール編集

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_search.scss, app/assets/stylesheets/modules/_top_content.scss, app/controllers/products_controller.rb, app/views/home/_brand_content.html.haml, app/views/home/_category_content.html.haml, app/views/home/_header.html.haml, app/views/home/_products.haml, app/views/home/index.html.haml, app/views/products/search.html.haml, config/breadcrumbs.rb, config/routes.rb
【サーバサイド】商品検索Lv1
トップページからキーワードで商品を検索できるようにするため。
利便性向上の為。
=> ProductSearch

app/controllers/products_controller.rb, app/views/products/item_show.html.haml
商品詳細のコメントのビューのエラー解消
正しく表示されるようにするため
=> debug missing template and controller

db/seeds.rb
seeds.rbファイルの変更
最終発表簡単査定demo用のデータ作成
商品データを編集:購入済みステータスとバイヤーの付与
=> Edit seeds

app/controllers/products_controller.rb, app/views/products/_product_user-item.haml, app/views/products/item_show.html.haml, app/views/products/show.html.haml
出品した商品の画像表示のバグ修正
商品詳細の関連商品の値段を3桁区切りに修正、リンクの飛び先の追加
視認性を高めるため
ユーザーが商品を回遊できるようにするため
=> Debug item show view

app/views/comments/_comment.html.haml, db/seeds.rb
=> debug comment error

db/seeds.rb
=> Change seed

app/assets/javascripts/application.js, app/assets/javascripts/jpostal.js, app/assets/javascripts/jquery.jpostal.js, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/address.html.haml, app/views/users/set_user.html.haml
住所自動入力機能の追加
よりスムーズにユーザー登録を行えるようにするため
=> Auto address input

app/assets/javascripts/product_exhibit.js, app/assets/javascripts/product_image_upload.js, app/assets/stylesheets/modules/_form.scss, app/controllers/products_controller.rb, app/views/products/edit.html.haml, app/views/products/new.html.haml, db/seeds.rb
商品出品・編集ページの編集
controller,view,javascript
商品出品ページカテゴリ入力フォーム部分の条件分岐表示
商品編集ページカテゴリ入力フォーム部分の条件分岐表示と元の情報のセット
孫カテゴリと合わせてブランドとサイズフォームを表示
商品編集ページ画像、edit表示時にDB削除をしないように修正（保存方法は前回のままで、再度保存が必要な状態。）
=> Exhibit category display
